#!/usr/bin/env bash

source ../../ENVIRONMENT_VARIABLES
source ./functions
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`


CELL_DIM=4.635
CUTOFF=40
nbnd=20
PREFIX=Grafene

##################################################################################################
#Conto scf
print_scf_in;

IN="$PREFIX.scf.in"
OUT="$PREFIX.scf.out"
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x < $IN > $OUT"
echo "$COMMAND"
$COMMAND < $IN > $OUT

mv $OUT tmp 

rm -r tmp/$PREFIX.save/K*
rm -fr tmp_scf
mv tmp tmp_scf

##################################################################################################
#Convergenza sui punti k
for k_pt in 15 21 30; do
	cp -r tmp_scf tmp
	DIRNAME="kpt_$k_pt"

	#Conti nscf
	print_nscf_in $k_pt;

	IN="$PREFIX.kpt_$k_pt.nscf.in"
	OUT="$PREFIX.kpt_$k_pt.nscf.out"
	COMMAND="$RUN_COMMAND $BIN_DIR/pw.x < $IN > $OUT"
	echo "  $COMMAND"
	$COMMAND < $IN > $OUT

	mkdir -p $DIRNAME
#mv -t $DIRNAME $OUT tmp
	mv $OUT $DIRNAME
	mv tmp $DIRNAME
	cd $DIRNAME

	#Conti proprieta ottiche (Parte immaginaria della funzione dielettrica)
	print_pw2gw_in

	IN="$PREFIX.pw2gw.in"
	OUT="$PREFIX.pw2gw.out"
	COMMAND="  $BIN_DIR/pw2gw.x < $IN > $OUT"
	echo "$COMMAND"
	$COMMAND < $IN > $OUT
	
	cd ..
	echo -e "\n"
done


##################################################################################################
#Convergenza sul numero di bande
for nbnd in 5 10 15; do
	cp -r tmp_scf tmp
	DIRNAME="bnd_$nbnd"

	#Conti nscf
	print_nscf_in2 $nbnd;

	IN="$PREFIX.bnd_$nbnd.nscf.in"
	OUT="$PREFIX.bnd_$nbnd.nscf.out"
	COMMAND="$RUN_COMMAND $BIN_DIR/pw.x < $IN > $OUT"
	echo "  $COMMAND"
	$COMMAND < $IN > $OUT

	mkdir -p $DIRNAME
#mv -t $DIRNAME $OUT tmp
	mv $OUT $DIRNAME
	mv tmp $DIRNAME
	cd $DIRNAME

	#Conti proprieta ottiche (Parte immaginaria della funzione dielettrica)
	print_pw2gw_in

	IN="$PREFIX.pw2gw.in"
	OUT="$PREFIX.pw2gw.out"
	COMMAND="  $BIN_DIR/pw2gw.x < $IN > $OUT"
	echo "$COMMAND"
	$COMMAND < $IN > $OUT
	
	cd ..
	echo -e "\n"
done


exit





