#!/usr/bin/env bash

source ../../ENVIRONMENT_VARIABLES
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

SAVE=binding_energy.dat
echo -e "#Spin\tCO(Ry)\t\tC(Ry)\t\tO(Ry)\t\tBE(eV)" > $SAVE

echo -e "\tStart: " `date`
# No spin
IN=co-nospin.scf.in
OUT=co-nospin.scf.out
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT

ENERGY1=`cat $OUT | grep ! | tr -dc '0-9,-.'`

IN=c-nospin.scf.in
OUT=c-nospin.scf.out
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT

ENERGY2=`cat $OUT | grep ! | tr -dc '0-9,-.'`

IN=o-nospin.scf.in
OUT=o-nospin.scf.out
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT

ENERGY3=`cat $OUT | grep ! | tr -dc '0-9,-.'`

BE=`echo "scale=4;($ENERGY1 - $ENERGY2 - $ENERGY3 )*27.2114/2" | bc -l`

echo -e "NoSpin\t$ENERGY1\t$ENERGY2\t$ENERGY3\t $BE" >> $SAVE

# Spin polarization
IN=co-spin.scf.in
OUT=co-spin.scf.out
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT

ENERGY1=`cat $OUT | grep ! | tr -dc '0-9,-.'`

IN=c-spin.scf.in
OUT=c-spin.scf.out
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT

ENERGY2=`cat $OUT | grep ! | tr -dc '0-9,-.'`

IN=o-spin.scf.in
OUT=o-spin.scf.out
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT

ENERGY3=`cat $OUT | grep ! | tr -dc '0-9,-.'`

BE=`echo "scale=4;($ENERGY1 - $ENERGY2 - $ENERGY3 )*27.2114/2" | bc -l`

echo -e "Spin\t$ENERGY1\t$ENERGY2\t$ENERGY3\t $BE" >> $SAVE

# Spin polarization, no symmetry
IN=co-nosym.scf.in
OUT=co-nosym.scf.out
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT

ENERGY1=`cat $OUT | grep ! | tr -dc '0-9,-.'`

IN=c-nosym.scf.in
OUT=c-nosym.scf.out
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT

ENERGY2=`cat $OUT | grep ! | tr -dc '0-9,-.'`

IN=o-nosym.scf.in
OUT=o-nosym.scf.out
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT

ENERGY3=`cat $OUT | grep ! | tr -dc '0-9,-.'`

BE=`echo "scale=4;($ENERGY1 - $ENERGY2 - $ENERGY3 )*27.2114/2" | bc -l`


echo -e "NoSym\t$ENERGY1\t$ENERGY2\t$ENERGY3\t $BE" >> $SAVE

echo -e "\tEnd: " `date`

echo "Run completed at: " `date`
exit

cat > plot.gnu <<EOF
#!/usr/bin/gnuplot

set term wxt enhanced

set xlabel "E_{cut} (Ry)"
set ylabel "Bond lenght (bohr)"

plot \
	'$SAVE'  u 1:2 w lp pt 7 lw 2  lc rgb "black" title "bondl vs E_{cut}"
	

pause -1
set term pdfcairo enhanced
set output "bond_length.pdf"
replot

set term wxt enhanced

set xlabel "E_{cut} (Ry)"
set ylabel "E_{tot} (Ry)"

plot \
	'$SAVE1'  u 1:2 w lp pt 7 lw 2  lc rgb "black" title "E_{tot} vs E_{cut}"

pause -1
set term pdfcairo enhanced
set output "total_energy.pdf"
replot
EOF

gnuplot plot.gnu


exit



