#!/usr/bin/env bash

source ../../ENVIRONMENT_VARIABLES
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

for size in 5 12 
do

# self-consistent calculation
cat > co_script.relax.in << EOF
&CONTROL
  calculation  = "relax",
  prefix       = "CO",
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
  etot_conv_thr = 1.0D-4
  forc_conv_thr = 1.0D-3
  wf_collect=.true.
/
&SYSTEM
  ibrav     = 0,
  nat       = 2,
  ntyp      = 2,
  nbnd      = 6,
  ecutwfc   = 35 
/
&ELECTRONS
  conv_thr    = 1.D-7,
  mixing_beta = 0.7D0,
/
&IONS
  ion_dynamics = "bfgs"
/
CELL_PARAMETERS {bohr}
$size  0.0  0.0
 0.0 $size  0.0
 0.0  0.0 $size
ATOMIC_SPECIES
O  1.00  O.pw-mt_fhi.UPF
C  1.00  C.pw-mt_fhi.UPF
ATOMIC_POSITIONS {bohr}
C  8.256  6.0  6.0
O  6.000  6.0  6.0  0 0 0
K_POINTS {Gamma}
EOF

$RUN_COMMAND $BIN_DIR/pw.x < co_script.relax.in > co.relax.out_size$size
echo "Run completed at: " `date`

for ib in 5 6 
do
cat > co_script.pp.in << EOF
&INPUTPP
prefix       = "CO",
outdir       = "$TMP_DIR",
plot_num     = 7
filplot      = "psi2.plot"
kpoint       = 1
kband        = $ib
lsign        =.true.
/
&PLOT
nfile     = 1
filepp(1) ="psi2.plot"
iflag     = 3
output_format = 5
fileout = "psi2_size${size}_ib${ib}.xsf"
/
EOF

$RUN_COMMAND $BIN_DIR/pp.x < co_script.pp.in > co.pp.out_size${size}_ib${ib}
echo "Run completed at: " `date`

done 

done
