#!/bin/bash

source ../../ENVIRONMENT_VARIABLES
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

SAVE=bondl_vs_size.dat
echo -e "# bondl(bohr) size(bohr)" > $SAVE

for size in 5 6 7 8 9 10 11 12 13 14 15; do

IN=co.relax.in
OUT=co.relax.out_size$size

# self-consistent calculation
cat > co.relax.in << EOF
&CONTROL
  calculation  = "relax",
  prefix       = "CO",
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
  etot_conv_thr = 1.0D-4
  forc_conv_thr = 1.0D-3
/
&SYSTEM
  ibrav     = 0,
  nat       = 2,
  ntyp      = 2,
  nbnd      = 6,
  ecutwfc   = 35 
/
&ELECTRONS
  conv_thr    = 1.D-7,
  mixing_beta = 0.7D0,
/
&IONS
  ion_dynamics = "bfgs"
/
CELL_PARAMETERS {bohr}
$size  0.0  0.0
 0.0 $size  0.0
 0.0  0.0 $size
ATOMIC_SPECIES
O  1.00  O.pw-mt_fhi.UPF
C  1.00  C.pw-mt_fhi.UPF
ATOMIC_POSITIONS {bohr}
C  2.256  0.0  0.0
O  0.000  0.0  0.0  0 0 0
K_POINTS {Gamma}
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
#$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`


BONDL=`cat $OUT | grep "ATOMIC_POS" -A 3 | tail -n 4 | grep "C   " | tr -s " " | cut -d" " -f2`
echo -e "$size\t\t$BONDL" >> $SAVE

done

echo "Run completed at: " `date`

cat > plot.gnu <<EOF
#!/usr/bin/gnuplot

set term wxt enhanced

set xlabel "Cell size (bohr)"
set ylabel "Bond lenght (bohr)"

plot \
	'$SAVE'  u 1:2 w lp pt 7 lw 2  lc rgb "black" title "bondl vs size" 

pause -1
set term pdfcairo enhanced
set output "${SAVE:0: -4}.pdf"
replot
EOF

gnuplot plot.gnu


exit



