#!/bin/bash

source ../../ENVIRONMENT_VARIABLES
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`


# self-consistent calculation
cat > si.scf.in << EOF
&CONTROL
  calculation  = "scf",
  prefix       = "Si",
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
  restart_mode = "from_scratch"
  tprnfor = .true.
  wf_collect=.true.
/
&SYSTEM
  ibrav     = 2,
  celldm(1) = 10.21,
  nat       = 2,
  ntyp      = 1,
  ecutwfc   = 20
  nbnd      = 5
/
&ELECTRONS
  conv_thr    = 1.D-8,
  mixing_beta = 0.7D0	,
/
ATOMIC_SPECIES
 Si  28.086  Si.pz-vbc.UPF
ATOMIC_POSITIONS
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS 
  10
   0.1250000  0.1250000  0.1250000   1.00
   0.1250000  0.1250000  0.3750000   3.00
   0.1250000  0.1250000  0.6250000   3.00
   0.1250000  0.1250000  0.8750000   3.00
   0.1250000  0.3750000  0.3750000   3.00
   0.1250000  0.3750000  0.6250000   6.00
   0.1250000  0.3750000  0.8750000   6.00
   0.1250000  0.6250000  0.6250000   3.00
   0.3750000  0.3750000  0.3750000   1.00
   0.3750000  0.3750000  0.6250000   3.00
EOF

IN=si.scf.in
OUT=si.scf.out
echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x < $IN > $OUT"
echo -e "\t\t$COMMAND"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`


# bands calculation
cat > si.bands.in << EOF
&CONTROL
  calculation  = "bands",
  prefix       = "Si",
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
  tprnfor = .true.
  wf_collect=.true.
/
&SYSTEM
  ibrav     = 2,
  celldm(1) = 10.21,
  nat       = 2,
  ntyp      = 1,
  ecutwfc   = 20
  nbnd      = 8 
/
&ELECTRONS
  conv_thr    = 1.D-8,
  mixing_beta = 0.7D0	,
/
ATOMIC_SPECIES
 Si  28.086  Si.pz-vbc.UPF
ATOMIC_POSITIONS
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS
   36
   0.5 0.5 0.5  1
   0.4 0.4 0.4  2
   0.3 0.3 0.3  3
   0.2 0.2 0.2  4
   0.1 0.1 0.1  5
   0.0 0.0 0.0  6
   0.0 0.0 0.1  7
   0.0 0.0 0.2  8
   0.0 0.0 0.3  9
   0.0 0.0 0.4 10
   0.0 0.0 0.5 11
   0.0 0.0 0.6 12
   0.0 0.0 0.7 13
   0.0 0.0 0.8 14
   0.0 0.0 0.9 15
   0.0 0.0 1.0 16
   0.0 0.1 1.0 17
   0.0 0.2 1.0 18
   0.0 0.3 1.0 19
   0.0 0.4 1.0 20
   0.0 0.5 1.0 21
   0.0 0.6 1.0 22
   0.0 0.7 1.0 23
   0.0 0.8 1.0 24
   0.0 0.9 1.0 25
   0.0 1.0 1.0 26
   0.0 0.9 0.9 27
   0.0 0.8 0.8 28
   0.0 0.7 0.7 29
   0.0 0.6 0.6 30
   0.0 0.5 0.5 31
   0.0 0.4 0.4 32
   0.0 0.3 0.3 33
   0.0 0.2 0.2 34
   0.0 0.1 0.1 35
   0.0 0.0 0.0 36
EOF

IN=si.bands.in
OUT=si.bands.out
echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`


cat > si.bandspp.in << EOF
&bands
    prefix = "Si",
    outdir='$TMP_DIR'
    filband='Sibands.dat'
    lsym=.true.
 /
EOF

IN=si.bandspp.in
OUT=si.bandspp.out
echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/bands.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

cat > si.plotband.in << EOF
Sibands.dat
-6.0 10.0
Sibands.xmgr
Sibands.ps
6.377
1 6.377
EOF

IN=si.plotband.in
OUT=si.plotband.out
echo -e "\tStart: " `date`
COMMAND="$BIN_DIR/plotband.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`

echo "Run completed at: " `date`



exit




