#!/bin/bash

source ../../ENVIRONMENT_VARIABLES
echo "BIN_DIR:" $BIN_DIR
echo "PSEUDO_DIR:" $PSEUDO_DIR
echo "TMP_DIR:" $TMP_DIR
echo "Parallel command:" $RUN_COMMAND
echo "Started at: " `date`

SAVE=E_vs_grid.dat
echo -e "# N(NxNxN grid) energy(Ry)" > $SAVE

for grid in 2 4 6 8 12; do

IN=si_script.scf.in
OUT=si_script.scf.out_grid$grid

# self-consistent calculation
cat > si_script.scf.in << EOF
&CONTROL
  calculation  = "scf",
  prefix       = "Si",
  pseudo_dir   = "$PSEUDO_DIR",
  outdir       = "$TMP_DIR",
  restart_mode = "from_scratch"
  tprnfor = .true.
  wf_collect=.true.
/
&SYSTEM
  ibrav     = 2,
  celldm(1) = 10.21,
  nat       = 2,
  ntyp      = 1,
  ecutwfc   = 20
  nbnd      = 5
/
&ELECTRONS
  conv_thr    = 1.D-8,
  mixing_beta = 0.7D0	,
/
ATOMIC_SPECIES
 Si  28.086  Si.pz-vbc.UPF
ATOMIC_POSITIONS
 Si 0.00 0.00 0.00
 Si 0.25 0.25 0.25
K_POINTS {automatic}
$grid $grid $grid 1 1 1
EOF

echo -e "\tStart: " `date`
COMMAND="  $RUN_COMMAND $BIN_DIR/pw.x"
echo -e "\t\t$COMMAND < $IN > $OUT"
$COMMAND < $IN > $OUT
echo -e "\tEnd: " `date`


ENERGY=`cat $OUT | grep ! | tr -dc '0-9,-.'`
echo -e "$grid\t\t$ENERGY" >> $SAVE

done

echo "Run completed at: " `date`

cat > plot.gnu <<EOF
#!/usr/bin/gnuplot

set term wxt enhanced

set xlabel "N (NxNxN k-point mesh)"
set ylabel "E_{tot} (Ry)"

plot \
	'$SAVE'  u 1:2 w lp pt 7 lw 2  lc rgb "black" title "E vs NxNxN" 

pause -1
set term pdfcairo enhanced
set output "${SAVE:0: -4}.pdf"
replot
EOF

gnuplot plot.gnu


exit




